

typeset -U path cdpath fpath manpath

for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/amp4gjzznl8zschcxs74jqif5kd1y89b-zsh-5.9/share/zsh/$ZSH_VERSION/help"





# Oh-My-Zsh/Prezto calls compinit during initialization,
# calling it twice causes slight start up slowdown
# as all $fpath entries will be traversed again.



# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git rbenv)

ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh





# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


stty stop undef
stty start undef
setopt noflowcontrol

export TERM=alacritty
[ -n "$TMUX" ] && export TERM=tmux-256color
source "$(fzf-share)/key-bindings.zsh"

case $TERM in
screen*)
precmd(){
# Restore tmux-title to 'zsh'
printf "\033kzsh\033\\"
# Restore urxvt-title to 'zsh'
print -Pn "\e]2;zsh:%~\a"
}
preexec(){
# set tmux-title to running program
printf "\033k$(echo "$1" | cut -d" " -f1)\033\\"
# set urxvt-title to running program
print -Pn "\e]2;zsh:$(echo "$1" | cut -d" " -f1)\a"
          }
;;
esac

color-ssh() {
trap "colorterm.sh" INT EXIT
if [[ "$*" =~ "prod" ]]; then
colorterm.sh prod
elif [[ "$*" =~ "dev" ]]; then
colorterm.sh dev
elif [[ "$*" =~ "ghedamat-roof" ]]; then
colorterm.sh ghedamat-roof
else
colorterm.sh other
fi
ssh $*
}
compdef _ssh color-ssh=ssh

export FZF_DEFAULT_COMMAND='fd --type f --exclude .git'


# Aliases
alias -- ssh=color-ssh
alias -- vi=nvim
alias -- vim=nvim
alias -- vimdiff='nvim -d'

# Named Directory Hashes




