[colors.bright]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xdcdfe4"

[env]
term = "xterm-256color"

[font]
size = 13
[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[terminal.shell]
program = "/nix/store/amp4gjzznl8zschcxs74jqif5kd1y89b-zsh-5.9/bin/zsh"
